FantasyNameGen/Models/Name.cs
namespace FantasyNameGen.Models
{
    public class Name
    {
        public int Id { get; set; }
        public string RomanName { get; set; } // собственно имя
        public string CyrilName { get; set; } // транскрипция на русском
        public char Gender { get; set; } // пол (м/ж)
        public string Variants { get; set; } // вариации
        public string Description { get; set; } // описание
        public bool Common { get; set; } // распространённое
    }
}

FantasyNameGen/Controllers/NamesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FantasyNameGen.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FantasyNameGen.Controllers
{
    public class NamesController : Controller
    {
        private NamesContext db;
        private SurnamesContext dbs;
        public NamesController(NamesContext context, SurnamesContext scontext)
        {
            db = context;
            dbs = scontext;
        }
        // GET: Names
        public async Task<IActionResult> Index()
        {
            return View(await db.Names.OrderByDescending(s => s.Id).ToListAsync());
            //return RedirectToAction("GetRandom");
        }

        // GET: Names
        public async Task<IActionResult> GetRandom()
        {
            return View(await db.Names.ToListAsync());
        }

        [HttpPost]
        public IActionResult Random(char gender, char common, bool needSurname)
        {
            char all = 'у';
            List<Name> genderNames = new List<Name>();
            if (common == '3')
            {
                if (gender != 'а')
                    genderNames = db.Names.Where(p => (p.Gender == gender|| p.Gender == all)).ToList();
                else
                    genderNames = db.Names.ToList();
            }
            else
            {
                if (common == '1')
                {
                    if (gender != 'а')
                        genderNames = db.Names.Where(p => p.Common == true).Where(p => (p.Gender == gender || p.Gender == all)).ToList();
                    else
                        genderNames = db.Names.Where(p => p.Common == true).ToList();
                }
                if (common == '2')
                {
                    List<Name> commonGenderNames = new List<Name>();
                    if (gender != 'а')
                    {
                        genderNames = db.Names.Where(p => (p.Gender == gender || p.Gender == all)).ToList();
                        commonGenderNames = db.Names.Where(p => p.Common == true).Where(p => (p.Gender == gender || p.Gender == all)).ToList();
                    }
                    else
                    {
                        genderNames = db.Names.ToList();
                        commonGenderNames = db.Names.Where(p => p.Common == true).ToList();
                    }
                    genderNames.AddRange(commonGenderNames);
                }
            }

            int randomNameId = CryptoRandom.Random(genderNames.Count);
            
            NameSurnameViewModel nameSurname = new NameSurnameViewModel();
            nameSurname.Name = db.Names.FirstOrDefault(p => p.Id == genderNames[randomNameId].Id);
            nameSurname.Surname = new Surname() { RomanSurname = "", CyrilSurname = "", Common = false, Id = 0 };
            if (needSurname)
            {
                List<Surname> surnamesList = new List<Surname>();
                surnamesList = dbs.Surnames.ToList();
                int randomSurnameId = CryptoRandom.Random(surnamesList.Count);
                nameSurname.Surname = dbs.Surnames.FirstOrDefault(p => p.Id == surnamesList[randomSurnameId].Id);
            }

            return PartialView("/Views/Names/_Random.cshtml", nameSurname);
            //return PartialView("/Views/Home/Contact.cshtml");
        }

        // POST: Names/ChangeCommon
        //[HttpPost]
        public void ChangeCommon(int id)
        {
            Name s = db.Names.FirstOrDefault(p => p.Id == id);
            s.Common = !s.Common;
            db.Names.Update(s);
            db.SaveChanges();
            return;
        }
        // GET: Names/Details/5
        public ActionResult Details(int id)
        {
            Name s = db.Names.FirstOrDefault(p => p.Id == id);
            return View(s);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Name name)
        {
            db.Names.Add(name);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Names/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Names/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Names/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Names/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

FantasyNameGen/Views/Names/Create.cshtml
@model FantasyNameGen.Models.Name
@{
    ViewBag.Title = "Добавление имени";
}
<form asp-action="create" asp-controller="home">
    <div class="form-group">
        <label asp-for="RomanName" class="control-label">Имя</label>
        <input type="text" asp-for="RomanName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="CyrilName" class="control-label">Транскрипция</label>
        <input type="text" asp-for="CyrilName" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Gender" class="control-label">Пол</label>
        <input type="text" asp-for="Gender" class="form-control" />
    </div>   
    <div class="form-group">
        <label asp-for="Variants" class="control-label">Варианты</label>
        <input type="text" asp-for="Variants" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label">Описание</label>
        <input type="text" asp-for="Description" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-default" />
    </div>
</form>

FantasyNameGen/Views/Names/Details.cshtml
@model FantasyNameGen.Models.Name
@{
    ViewBag.Title = "NAME";
}
<h1>@Model.RomanName</h1>
<p>Транскрипция: <strong>@Model.CyrilName</strong></p>

@switch (@Model.Gender)
{
    case 'м':
        <p>Пол: мужской</p>
        break;

    case 'ж':
        <p>Пол: женский</p>
        break;

    case 'у':
        <p>Пол: универсальный</p>
        break;
}
<p>Варианты: @Model.Variants</p>
<p>@Model.Description</p>

FantasyNameGen/Views/Names/GetRandom.cshtml
@model IEnumerable<FantasyNameGen.Models.Name>
@{
    ViewBag.Title = "Генерируем английское имя!";
}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


<h1>Выберите параметры английского имени:</h1>

@using (Html.BeginForm("Random", "Names", FormMethod.Post))
{
<div class="container">
    <div class="row">
        <div class="col-xs-6 col-md-4 col-lg3">
            <label for="Gender">Выберите пол:</label>
            <br />
            @Html.RadioButton("Gender", "м")
            <span>Мужской</span> <br />
            @Html.RadioButton("Gender", "ж")
            <span>Женский</span> <br />
            @Html.RadioButton("Gender", "а", true)
            <span>Любой</span>
        </div>
        <div class="col-xs-6 col-md-4 col-lg3">
            <label for="Common">Выберите пол:</label>
            <br />
            @Html.RadioButton("Common", "1")
            <span>Только распространённые</span> <br />
            @Html.RadioButton("Common", "2")
            <span>Все с учётом распространённости</span> <br />
            @Html.RadioButton("Common", "3", true)
            <span>Все с равными шансами</span>
        </div>
    </div>   
    <div class="row">
        <div class="col-xs-6 col-xs-offset-2">
            @Html.CheckBox("needSurname", false)
            <label for="needSurname">также сгенерить фамилию</label>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 col-xs-offset-2">
            <input type="submit" value="Получить имя" id="RandomSubmit" />
        </div>
    </div>
</div>

}

<div id="randomDetails">
</div>
<script type="text/javascript" on-content-loaded="true">
$(document).ready(function () {
    $("#RandomSubmit").click(function (e) {
        e.preventDefault();
        $("#RandomSubmit").prop('disabled', true);
        $.ajax({
            url: "Names/Random",
            type: 'POST',
            data: {
                "gender": $('input[name=Gender]:checked').val(),
                "common": $('input[name=Common]:checked').val(),
                "needSurname": $('input#needSurname').prop('checked')
            },
            success: function (response) {
                $("#randomDetails").html(response);
                $("#RandomSubmit").prop('disabled', false);
            }
        });
    })
});
</script>

FantasyNameGen/Views/Names/Index.cshtml
@model IEnumerable<FantasyNameGen.Models.Name>
@{
    ViewBag.Title = "Все имена";
}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" on-content-loaded="true">
$(document).ready(function () {
    $(".ChangeCommonBtn").click(function (e) {
        e.preventDefault();
        $.ajax({
            url: $(this).attr("href"),
            success: function () {
                
            }
        }); return false;
    })
});
</script>

<a asp-action="Create">Добавить имя</a>
<table class="table">
    <tr><td>Common?</td><td>Имя</td><td>Транскрипция</td><td>Пол</td><td>Варианты</td><td>Описание</td></tr>
    @foreach (var item in Model)
    {
        <tr><td>@Html.ActionLink(@item.Common.ToString(), "ChangeCommon", "Names", new { id = item.Id }, new { @class = "ChangeCommonBtn" })</td><td>@item.RomanName</td><td>@item.CyrilName</td><td>@item.Gender</td><td>@item.Variants</td><td>@item.Description</td></tr>
    }
</table>

FantasyNameGen/Views/Names/_Random.cshtml
@model NameSurnameViewModel
@{
    ViewBag.Title = "RANDOM NAME";
}

<h1>@Model.Name.RomanName @Model.Surname.RomanSurname</h1>
<p>Транскрипция: <strong>@Model.Name.CyrilName @Model.Surname.CyrilSurname</strong></p>

@switch (@Model.Name.Gender)
{
    case 'м':
        <p>Пол: мужской</p>
        break;

    case 'ж':
        <p>Пол: женский</p>
        break;

    case 'у':
        <p>Пол: универсальный</p>
        break;
}
@if (!String.IsNullOrEmpty(@Model.Name.Variants))
{
    <p>Варианты: @Model.Name.Variants</p>
}
<p>@Model.Name.Description</p>