FantasyNameGen/Models/Surname.cs
namespace FantasyNameGen.Models
{
    public class Surname
    {
        public int Id { get; set; }
        public string RomanSurname { get; set; } // собственно имя
        public string CyrilSurname { get; set; } // транскрипция на русском
        public bool Common { get; set; } // распространённое
    }
}

FantasyNameGen/Controllers/SurnamesController.cs
using System.Linq;
using System.Threading.Tasks;
using FantasyNameGen.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FantasyNameGen.Controllers
{
    public class SurnamesController : Controller
    {
        private SurnamesContext dbs;
        public SurnamesController(SurnamesContext context)
        {
            dbs = context;
        }

        // GET: Surnames
        public async Task<IActionResult> Index()
        {
            return View(await dbs.Surnames.OrderByDescending(s => s.Id).ToListAsync());
            //return RedirectToAction("GetRandom");
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Surname surname)
        {
            dbs.Surnames.Add(surname);
            await dbs.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // POST: Surnames/ChangeCommon
        //[HttpPost]
        public void ChangeCommon(int id)
        {
            Surname s = dbs.Surnames.FirstOrDefault(p => p.Id == id);
            s.Common = !s.Common;
            dbs.Surnames.Update(s);
            dbs.SaveChanges();
            return;
        }


    }
}

FantasyNameGen/Views/Surnames/Create.cshtml
@model FantasyNameGen.Models.Surname
@{
    ViewBag.Title = "Добавление фамилии";
}
<form asp-action="create" asp-controller="surnames">
    <div class="form-group">
        <label asp-for="RomanSurname" class="control-label">Фамилия</label>
        <input type="text" asp-for="RomanSurname" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="CyrilSurname" class="control-label">Транскрипция</label>
        <input type="text" asp-for="CyrilSurname" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-default" />
    </div>
</form>

FantasyNameGen/Views/Surnames/Details.cshtml
@model FantasyNameGen.Models.Name
@{
    ViewBag.Title = "NAME";
}
<h1>@Model.RomanName</h1>
<p>Транскрипция: <strong>@Model.CyrilName</strong></p>

@switch (@Model.Gender)
{
    case 'м':
        <p>Пол: мужской</p>
        break;

    case 'ж':
        <p>Пол: женский</p>
        break;

    case 'у':
        <p>Пол: универсальный</p>
        break;
}
<p>Варианты: @Model.Variants</p>
<p>@Model.Description</p>

FantasyNameGen/Views/Surnames/Index.cshtml
@model IEnumerable<FantasyNameGen.Models.Surname>
@{
    ViewBag.Title = "Все фамилии";
}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

<script type="text/javascript" on-content-loaded="true">
$(document).ready(function () {
    $(".ChangeCommonBtn").click(function (e) {
        e.preventDefault();
        $.ajax({
            url: $(this).attr("href"),
            success: function () {
                
            }
        }); return false;
    })
});
</script>

<a asp-action="Create">Добавить фамилию</a>
<table class="table">
    <tr><td>Common?</td><td>Фамилия</td><td>Транскрипция</td></tr>
    @foreach (var item in Model)
    {
        <tr><td>@Html.ActionLink(@item.Common.ToString(), "ChangeCommon", "Surnames", new { id = item.Id }, new { @class = "ChangeCommonBtn" })</td><td>@item.RomanSurname</td><td>@item.CyrilSurname</td></tr>
    }
</table>